# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sysb_dacadc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sysb_dacadc.proto\"\x96\x01\n\x07\x43ommand\x12\x1a\n\x04name\x18\x01 \x01(\x0e\x32\x0c.CommandName\x12\x1c\n\tdac_state\x18\x02 \x01(\x0b\x32\t.DacState\x12\x1c\n\tadc_state\x18\x03 \x01(\x0b\x32\t.AdcState\x12\x1c\n\tsel_state\x18\x04 \x01(\x0b\x32\t.SelState\x12\x15\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x06.Error\"7\n\x08\x44\x61\x63State\x12\x1c\n\x07\x63hannel\x18\x01 \x01(\x0e\x32\x0b.ChannelNum\x12\r\n\x05value\x18\x02 \x01(\x02\"8\n\x08SelState\x12\x14\n\x03num\x18\x01 \x01(\x0e\x32\x07.SelNum\x12\x16\n\x03val\x18\x02 \x01(\x0e\x32\t.LogicVal\"7\n\x08\x41\x64\x63State\x12\x1c\n\x07\x63hannel\x18\x01 \x01(\x0e\x32\x0b.ChannelNum\x12\r\n\x05value\x18\x02 \x01(\x05\"2\n\x05\x45rror\x12\x18\n\x04\x63ode\x18\x01 \x02(\x0e\x32\n.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t*@\n\x0b\x43ommandName\x12\x11\n\rWRITE_CFG_DAC\x10\x00\x12\x0f\n\x0bREAD_SS_ADC\x10\x01\x12\r\n\tWRITE_SEL\x10\x02*m\n\nChannelNum\x12\x11\n\rCHANNEL_NUM_0\x10\x00\x12\x11\n\rCHANNEL_NUM_1\x10\x01\x12\x11\n\rCHANNEL_NUM_2\x10\x02\x12\x11\n\rCHANNEL_NUM_3\x10\x03\x12\x13\n\x0f\x43HANNEL_NUM_ALL\x10\x04*&\n\x06SelNum\x12\r\n\tSEL_NUM_1\x10\x00\x12\r\n\tSEL_NUM_2\x10\x01*$\n\x08LogicVal\x12\x0b\n\x07LOGIC_0\x10\x00\x12\x0b\n\x07LOGIC_1\x10\x01*S\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x43RC\x10\x01\x12\x0c\n\x08\x44\x45\x43ODING\x10\x02\x12\x10\n\x0cOUT_OF_RANGE\x10\x03\x12\x15\n\x11MISSING_PARAMETER\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sysb_dacadc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMMANDNAME']._serialized_start=398
  _globals['_COMMANDNAME']._serialized_end=462
  _globals['_CHANNELNUM']._serialized_start=464
  _globals['_CHANNELNUM']._serialized_end=573
  _globals['_SELNUM']._serialized_start=575
  _globals['_SELNUM']._serialized_end=613
  _globals['_LOGICVAL']._serialized_start=615
  _globals['_LOGICVAL']._serialized_end=651
  _globals['_ERRORCODE']._serialized_start=653
  _globals['_ERRORCODE']._serialized_end=736
  _globals['_COMMAND']._serialized_start=22
  _globals['_COMMAND']._serialized_end=172
  _globals['_DACSTATE']._serialized_start=174
  _globals['_DACSTATE']._serialized_end=229
  _globals['_SELSTATE']._serialized_start=231
  _globals['_SELSTATE']._serialized_end=287
  _globals['_ADCSTATE']._serialized_start=289
  _globals['_ADCSTATE']._serialized_end=344
  _globals['_ERROR']._serialized_start=346
  _globals['_ERROR']._serialized_end=396
# @@protoc_insertion_point(module_scope)
